services:
  backend2lab:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "4000:4000"
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/modules"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend2lab-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "4001:4000"
      - "4201:4200"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    command: sh -c "pnpm run dev"
    profiles:
      - dev
